import puppeteer from "puppeteer";
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BRIEF_DIR = path.join(__dirname, "briefs");
const OUTPUT_DIR = path.join(__dirname, "output");
const TEMPLATE_DIR = path.join(__dirname, "templates");

// Map persona IDs to their visual template
const TEMPLATE_MAP = {
  "startup-cto": "startup-cto.html",
  "eng-manager-growth": "eng-manager.html",
  "vp-finance": "vp-finance.html",
  "solo-founder": "solo-founder.html",
  "vp-product-platform": "vp-product.html",
};

// Subline copy per persona (not generated by LLM — designed for the visual)
const SUBLINE_MAP = {
  "startup-cto": "Ship your product, not your payments stack.",
  "eng-manager-growth": "Incremental migration. Zero downtime.",
  "vp-finance": "Automate reconciliation, disputes, and revenue recognition.",
  "solo-founder": "From zero to first customer in minutes.",
  "vp-product-platform": "Powering payments for the world's leading platforms.",
};

async function main() {
  console.log("\n\u2501\u2501\u2501 Peitho Render Pipeline \u2014 Stripe Campaign v2 \u2501\u2501\u2501\n");

  const briefFiles = (await fs.readdir(BRIEF_DIR)).filter((f) => f.endsWith(".json"));
  if (briefFiles.length === 0) {
    console.error("No briefs found. Run `npm run generate` first.");
    process.exit(1);
  }

  console.log(`Found ${briefFiles.length} briefs to render.\n`);
  await fs.mkdir(OUTPUT_DIR, { recursive: true });

  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  for (const file of briefFiles) {
    const brief = JSON.parse(await fs.readFile(path.join(BRIEF_DIR, file), "utf-8"));
    const personaId = brief.personaId;

    const templateFile = TEMPLATE_MAP[personaId];
    if (!templateFile) {
      console.log(`  \u2717 Skipping ${personaId} — no template mapped`);
      continue;
    }

    console.log(`  \u25b8 Rendering: ${personaId} (${templateFile})`);
    console.log(`    Headline: "${brief.creative.headline}"`);

    let html = await fs.readFile(path.join(TEMPLATE_DIR, templateFile), "utf-8");

    // Inject headline
    html = html.replace(
      '<div class="headline" id="headline"></div>',
      `<div class="headline" id="headline">${brief.creative.headline}</div>`
    );

    // Inject subline
    const subline = SUBLINE_MAP[personaId] || "";
    html = html.replace(
      '<div class="subline" id="subline"></div>',
      `<div class="subline" id="subline">${subline}</div>`
    );

    // Inject subtext
    if (brief.creative.subtext) {
      html = html.replace(
        /id="subtext">[^<]*</,
        `id="subtext">${brief.creative.subtext}<`
      );
    }

    const page = await browser.newPage();
    await page.setViewport({ width: 1080, height: 1080, deviceScaleFactor: 2 });
    await page.setContent(html, { waitUntil: "networkidle0" });
    await page.evaluateHandle("document.fonts.ready");

    const outPath = path.join(OUTPUT_DIR, `${personaId}-ad.png`);
    await page.screenshot({
      path: outPath,
      type: "png",
      clip: { x: 0, y: 0, width: 1080, height: 1080 },
    });

    await page.close();
    console.log(`    \u2713 Saved: ${outPath}\n`);
  }

  await browser.close();
  console.log(`\u2501\u2501\u2501 Done \u2014 ${briefFiles.length} ads rendered \u2501\u2501\u2501\n`);
}

main().catch((err) => {
  console.error("Render failed:", err);
  process.exit(1);
});
